<<<<<<< HEAD
title: Leaf Blog
iconURL: assets/default-icon.png
theme: jekyll-theme-leaf

# for a clean URL
permalink: :slug

social:
  twitter: _SupunKavinda
  github: SupunKavinda

plugins:
 - jekyll-feed
 - jekyll-seo-tag

### comments & analytics
hyvor_talk_website_id: 14
google_analytics: UA-NNNNNNNN-N
=======
theme: jekyll-theme-minimal
>>>>>>> 83573c1071aeb1ee32e98a7f46fd8bb8a589b5a5
